### ISSUE TITLE
Can I visit this little program now?

### ISSUE THREAD

**Issue by mieruko0713** [airingursb/miemie#1]
It looks cute and interesting^_^。   
Would you like to upload a picture or provide a method of visiting it ?

**Comment by airingursb** [comment]
@maruko0713 I update the README.md, now you can see the screenshots and more detail of the  application.

The version is being reviewed by WeChat. If they pass the app, you will see it in WeChat. However, I know there are so many bugs to fix and more amazing features to develop.

If you are interested in it, can we develop it together? I will add your information in the view of authors' introduction.

Last but not least, can you speak Chinese?

**Comment by mieruko0713** [comment]
哈哈哈哈好的好的！！！   
非常可爱的一个应用看起来！！给你一个大大的赞！
如果能一起做就最好啦！！！
（我可以做些什么？）
（虽然还没有接触过微信小程序）
（立刻去学？？？！！！）

**Comment by airingursb** [comment]
@maruko0713 恩啊，那加微信还是qq？方便留一个以便联系吗？

**Comment by mieruko0713** [comment]
我的微信是Mcdull0713!^_^
啊啊啊不好意思这两天都和爸爸妈妈黏在一起守岁和拜年，今天才登上来回复你～～新年快乐！^_^

**Comment by cuijiudai** [comment]
字体文件没用吧，用的系统默认的Chalkboard
