### ISSUE TITLE
你好，我也想做一个类似的单词小程序，有几个问题想问一下

### ISSUE THREAD

**Issue by seven-share** [airingursb/miemie#5]
1. 我看到你小程序里有单词词库的js文件，我想问一下词库的js文件从哪里获取的? 
    因为我希望有四级，六级，雅思等不同的词库，我自己搜索了，有，但没有很理想的
2. 如果想加上单词音频的话，应该怎么做？
    我目前的做法可能是通过英语单词去使用谷歌或有道的api可以获取到音频，但感觉每次都去请求会很
    慢，希望可以将音频也放在本地，不知道有没有什么办法

希望可以帮忙解答一下，谢谢，十分感谢

**Comment by airingursb** [comment]
当时是爬取扇贝单词的词库做成的js文件，你可以再看看扇贝单词开放平台是否还提供api了，如果提供，可以继续爬，但是要注意速度谨防被ban。 @seven-share

**Comment by seven-share** [comment]
音频呢？也爬取下来？感觉音频不好做，每次请求翻译类api的话，感觉会很久才有回复，同时如果请求翻译类的api就不用自己储存中文意思了，就保存单词即可，关于音频不知道您有什么建议

**Comment by airingursb** [comment]
@seven-share 音频有url的，直接播放url的资源就行了

**Comment by seven-share** [comment]
嗯，谢谢，我自己搜了一遍api，可以返回音频url，因为我想在显示单词的同时，播放音频，所以我希望音频的播放延迟小一点，我想了三种方案，问题有点长，这里说不太清晰，我把详细的问题描述放在了这里，[问题网址](https://www.v2ex.com/t/450523#reply0)，希望您可以给点建议

**Comment by airingursb** [comment]
@seven-share 你的方案其实已经挺好的了。我觉得+cdn，一个音频就几十kb，完全可以接受

**Comment by Yijia-Zhou** [comment]
`"http://dict.youdao.com/dictvoice?audio=" + word`
延迟超低
